#+STYLE: <link rel="stylesheet" type="text/css" href="style.css" />
* 38 Emacs 显示

这单描述了Emacs 用户界面的几个特点。

** 刷新屏幕

`redraw-frame' 清除并重绘整个frame。这个函数在屏幕崩溃时特别有用。

函数： redraw-frame frame

这个函数清除并重绘 FRAME。

命令： redraw-display

这个函数清除并重绘所有可见的frame.

在Emacs 里面，处理用户输入的优先级高于屏幕显示，如果你在输入的时候调用 这些函数，它们不会立即起作用，但是在当输入被处理完成后，被要求的重绘任务会立马执行。

在文本终端，在暂停和唤醒 Emacs 的时候，通常也会重绘屏幕。有些终端模拟器会记录各个依赖于显示的程序的显示 内容。如果你在用这类终端，你可能需要禁止唤醒重绘。

用户设置： no-redraw-on-reenter

这个变量决定了 Emacs 在暂停并唤醒后是否重绘整个屏幕。 默认值是 `nil'，意思是需要重绘。否则是需要重绘。

** 强制重绘
   通常情况下，Emacs等待输入的过程中都在尝试重绘屏幕。通过以下的这些函数，你可以要求Emacs立即重绘，而不是等待输入。

   函数： redisplay &optional force
   这个函数要求立即重绘。可选的参数 FORCE ，如果不是 nil，强制redisplay执行，而不管变量`redisplay-dont-pause' 的值和输入是否在进行中。

   函数返回`t' 意味着函数已经执行过了，但是不代表执行成功了，反之亦然。它有可能是被新到 的输入给中断了。

   变量： redisplay-dont-pause
   如果这个变量的值是 `nil'，到达的输入事件会中断重绘；Emacs不会启动重绘，并且会停止所有在运行中的重绘过程，直到输入事件被处理完毕。这

   变量： redisplay-preemption-period
   决定Emacs在重显过程中每次检查输入间隔的时间，如果在这间隔中有输入，将停止重绘，并对输入进行处理，变量的默认值是0.1；如果值是nil，Emacs在重绘的过程中不会检查输入。
   
   但是这个变量在 redisplay-dont-pause 不是nil的时候是没有作用的。

虽然 redisplay 试图立即进行绘制，但是它不会改变Emacs对那部分frams进行绘制的决定。相反，下面这个函数会增加重绘任务，但是不会立即执行。

函数： force-window-update &optional object
这个函数强制Emacs在下次重绘时对部分或者全部的窗口进行重绘。如果OBJECT是一个窗口，则该窗口被重绘，如果OBJECT是frame，则其中的所有窗口都会被重绘。如果OBJECT是nil，所有的窗口会被重绘。

这个函数不会触发重绘立即执行。Emacs在等待输入的过程中或者redisplay函数被调用的时候才会处理这些任务。

** 长句截断
   
当一行文本的长度超过了窗口的最右边界，Emacs可能折行或者续行。续行不同于断行，续行只在显示上，而不是在buffer中，他在窗口的右边界精确地进行，而不是单词的边界。

在图形显示上，窗口的右边界上有一个小小的箭头表示这是一长行文字。在文本终端显示上，在最右列有一个`$'表示。

用户设置： truncate-lines
如果这个变量不是 nil，超过最右边界的文字会被截断显示，否则会折行显示。有一个例外是， truncate-partial-width-windows 变量的优先权大于 partial-width 变量。

用户设置： truncate-partial-width-windows

用户设置： wrap-prefix

** 回显区

回显区用于显示错误信息，message 函数输出和击键。它不同于minibuffer，尽管它们俩都出现在屏幕的相同地方。

*** 显示消息
    
    以下是用于在回显区显示信息的标准函数。
    函数： message format-string &rest arguments
    FORMAT-STRING 是格式字串， ARGUMENTS 是格式详述。函数的返回结果显示在回显区内，如果包含有`face'文本说明，就用设置的faces显示。同时，结果也会被添加至*Messages* buffer。

    在batch模式下，信息会被输出至标准错误流，以换行符结尾。

    如果 FORMAT-STRING 是空的，该函数清空回显区，设置回原来的大小。如果minibuffer处于激活状态，则显示minibuffer的内容。

    宏： with-temp-message message &rest body
    这个结构在执行 BODY 的过程中，在回显区内临时显示一条信息。

    函数： message-or-box format-string &rest arguments
    这个函数用一个对话框显示消息 MESSAGE.

    函数： message-box format-string &rest arguments
    如果用对话框显示不成功，则显示在回显区内。

    函数： display-message-or-buffer message &optional buffer-name not-this-window frame
    显示的内容可能是字符串或者buffer，如果长度大于回显区的宽度则重新弹出一个buffer予于显示。

    函数： current-message
    获得回显区内当前内容，如果为空则返回nil。

*** 自定义回显区

    以下变量用于控制回显区工作方式。
    变量： cursor-in-echo-area
    如果为nil，光标在point--不在回显区内，否则在消息的末尾。

    变量： echo-area-clear-hook
    这个钩子在回显区被清除的时候执行。

    用户设置： echo-keystrokes
    这个变量决定命令回显前等待的时间。必须是整数或者浮点数，代表秒。如果用户输入了前缀键（比如`C-x'），前缀键会在回显区内显示这么长的时间。

    如果其值为零，则输入命令不会显示。

    变量： message-truncate-lines
    如果变量值不是nil，显示区不会自动适应内容。

    变量 `max-mini-window-height'，用于设置minibuffer的最大高度，同样适用于回显区。

** 告警显示

   告警信息于用通知用户可能存在的问题，但是程序会继续运行。

*** 告警基础

    所有警告都有一个文本消息和一个严重程度标识。下面是可能的出现的严重程度，从上至下，严重程度降低。
    :emergency
    如果你不立即处置，Emacs会崩溃。
    :error
    报告数据或者环境所固有的错误。
    :warning
    报告数据或者环境可能引起的问题。
    :debug
    报告的信息只对你在debugging的时候有用。

    当你的程序遇到了非法的数据，它可以用`error'或者`signal'来发出消息。如果用发出Lisp error的方式，虽然最简单，但程序不能再继续运行。如果你遇到了用户错误的输入，还想保持程序继续运行，可以采用signal向用户报告严重程度为`:error'的告警信息。

    每个告警信息都有一个“warnig type“ 对其进行分类。种类是一个符号列表。第一个符号应该是自定义的用于存储用户设置的组（group）。比如，字节编译器用`(bytecomp)'作为其告警类型。只要你愿意，你可能继续细分告警类型，只是用更多的符号在来表示。

    函数： display-warning type message &optional level buffer-name

    函数： lwarn type level message &rest args

    函数： warn message &rest args
    这个函数用`(format MESSAGE ARGS...)'作为消息，`(emacs)作为类型，`:warning'作为严重程度。函数存在主要是为了兼容性考虑，不推荐用它，因为你应该设置一个明确的 warning type。
    
*** 告警变量

    通过设置以下的变量，你的程序可能自定义告警的呈现方式。

    变量： warning-levels
    这个表定义告警程度的意义和顺序。每个元素定义一个严重程度，以递减的顺序排列。

    每个元素的格式都是`(LEVEL STRING FUNCTION)'，LEVEL是定义的严重程度，STRING 是其的文本描述，STRING 应该用`%s'来设定放置告警种类信息的位置。

    变量： warning-prefix-function
    如果不是nil，它的值是一个用于产生告警前缀的函数。你可能把它绑定到一个合适的函数， display-warning 会调用它，把它的结果插入到当前的 warning buffer。

    绑定的函数应该有两个参数，严重程度和其在 warning-levels 中的入口。

    变量： warning-series

    变量： warning-fill-prefix

    变量： warning-type-format

*** 告警设置

    这些变量控制当一个lisp程度告警的时候Emacs的行为。
    用户设置: warning-minimum-level
    表示应该呈现给用户的最低严重程度的告警信息。默认值是`:warning'，即其会显示除了`:debug'信息之外的所有信息。

    用户设置： warning-minimum-log-level

    用户设置： warning-suppress-types

    用户设置： warning-suppress-log-types
    
*** 延迟告警
    有些时候，你可能希望在命令执行的时候还要显示告警信息，而是在其执行完毕之后显示。你可以用变量`delayed-warnings-list'来进行控制。

    变量： delayed-warnings-list
    这是一个延迟进行显示的告警信息的列表。每个元素都是一个列表：
    (TYPE MESSAGE [LEVEL [BUFFER-NAME]])
    当Emacs执行完`post-command-hook'后就会立即显示这个变量设置的所有告警信息。

    想要深度定制延迟告警机制的话，你可以修改 `delayed-warnings-hook'变量。

** 隐藏文本
   使用`invisible'属性，你可以使字符不可见，让它们不显示在屏幕上。这可以是文本属性，也可以是叠加属性。而且这些字符一般不会影响光标的移动；如果命令结束的地方在不可见区内，会把光标的位置定在文本的另一端。

   最简单的情况下，任何非nil的`invisible'属性将使字符不可见。如果你没有计划手动设置 `buffer-invisibility-spec'的话，你应该将`invisible'设置成`t'。
   更普遍的是，你可以用`buffer-invisibility-spec'来控制`invisible'值的意义。这允许你通过给文本设置不同的`invisible'值来把文本进行分类。

   通过`buffer-invisibility-spec'来控制文本的显示属性来显示数据库的条目时特别有用。因为你可以容易实现一个过滤器来查看数据库中的某一部分。设置这个变量非常快，比扫描buffer中的所有文本来改变其属性要快很多。

   变量： buffer-invisibility-spec
   `t'
   当`invisible'的值不是nil的时候，字符可见。
   列表
   列表中的每一个元素是一个显示的准则；如果一个字符的`invisible'属性与之匹配，那这个字符就不可见。列表可以有两种元素：
   ATOM
   如果字符的`invisible'属性值是ATOM或者其值是一个列表，但有一个成员是ATOM，则该字符不可见。

   （ATOM . t）
   与上一项同，但多个具有隐藏属性的字符会显示成省略号。
   
有两个函数用于给`buffer-invisibility-spec'添加和移除元素。

函数： add-to-invisibility-spec element
函数： remove-from-invisibility-spec element

一个约定俗成的用法是，一个主模式应该用该模式自己的名字作为`buffer-invisibility-spec'的一个元素，和`invisible'的值。

#+BEGIN_SRC elisp
     ;; 如果你想显示省略号 
     (add-to-invisibility-spec '(my-symbol . t))
     ;; 如果你不想显示省略号
     (add-to-invisibility-spec 'my-symbol)

     (overlay-put (make-overlay beginning end)
                  'invisible 'my-symbol)

     ;; When done with the invisibility:
     (remove-from-invisibility-spec '(my-symbol . t))
     ;; Or respectively:
     (remove-from-invisibility-spec 'my-symbol)
     ;; If you want to display an ellipsis:
     (add-to-invisibility-spec '(my-symbol . t))
     ;; If you don't want ellipsis:
     (add-to-invisibility-spec 'my-symbol)

     (overlay-put (make-overlay beginning end)
                  'invisible 'my-symbol)

     ;; When done with the invisibility:
     (remove-from-invisibility-spec '(my-symbol . t))
     ;; Or respectively:
     (remove-from-invisibility-spec 'my-symbol)
#+END_SRC

你可以用以下的函数的检查看不见的字符。

函数： invisible-p pos-or-prop
如果 POS-OR-PROP 是标记或者数字，函数返回non-`nil'来表示所指位置是不可见的。

如果 POS-OR-PROP 是其他 Lisp 对象，那可能是

** 选择显示

   选择显示指的是用于隐藏某一行的一组相关特征。

   第一种变体是，明确选择显示：通过修改文本的属性来控制行的隐显。这种隐藏在某方面有些像`invisible'属性的效果。

第二种变体，要隐藏的行是通过缩进自动选定的。这个变体是被设计成用户层特征。

你控制明确选择显示的方式是将新行符(control-j)替换成回车符(control-m)。回车符后面的行将隐藏。严格地说，它只是暂时不是一行了而已，它现在只是前面那一行的一部分了。

选择显示不会直接影响到编辑命令。

** 临时显示

   临时显示主要是Lisp程序在buffer中向用户展示相关信息但不提供编辑功能的方法。许多帮助命令使用这个特性。

   宏： with-output-to-temp-buffer buffer-name forms...
   这个函数先执行FORMS，然后将相关结果插入以BUFFER-NAME命名的buffer中，再将其置入Help模式。最后，在窗口中显示buffer,但是不处于选择状态。
   如果FORMS不改变输出窗口的主模式，所以在执行结束以后仍然是Help模式，

** 叠加
   你可以用叠加来改变buffer里面文本在屏幕上的外观。叠加是属于特定buffer的一个对象，它有指定的起始和结尾。它也具有可以检查和设置的属性，，这些属性影响叠加文本的显示。
   
叠加的视觉效果和文本属性是一样的。但是，因为实现不同，通常情况下，叠加的延展性不好（许多操作花费的时间和buffer中的叠加的数量是成正比的）。如果你想要改变buffer中许多片断的视觉效果，我们推荐用文本属性。

叠加用标记来记录它的开始和结尾，这样，编辑文本会调整它的开始和结尾。当你创建叠加，你可以设定在叠加起始位置插入的文本是属于叠加里面还是叠加外面，其尾部插入的文本也一样。

** 宽度

因为不是所有的字符都有相同的宽度，这些函数允许你检查字符的宽度。
函数： char-width char
该函数返回字符CHAR的所占的列数。
函数： string-width string
如果字符串STRING在当前窗口中，则返回其所占的列数。
函数： truncate-string-to-width string width &optional start-column padding ellipsis
该函数从STRING中截取WIDTH长度的新字符串。
如果STRING的长度小于WIDTH，则返回STRING。

** 行高

   行高是行内容高度和垂直行距之和。
   行内高是行中最高的字符或者是图片的高度，如果有新行的话还包括新行符。

   有许多方法可以设置更大的行高，要么设置绝对显示行高，要么设置行间距。但是，不管采取怎样的方法，实际的行距都不会比默认的小。

   可以用新行符的`line-height'文本属性或者叠加属性来控制其高度。

   如果该属性值为`t'，新行符不会影响该行行高，行高由行内容所决定。这对插入小的图片很有用，因为不用手动在图片之间添加空白行。

   如果该属性值是具如下形式的列表(HEIGHT TOTAL)，则会在当前行的下方添加额外的空白。首先，Emacs会用HEIGHT来控制当前行上方的额外空白，然后，它在他在其下方添加足够的空白来使总行高达到TOTAL。在这种情况下，所有其他设置行间距的方式都是无效的。
   
** 样式
   
   样式是显示文本的一系列图形属性的集合：字体，前景色，背景色，可选的下划线，等等。样式决定了文本以及mode line的显示方式。

   表示样式的一种方式是用列表，如（:foreground "red" :weight bold）。你可以将这样的匿名样式作为文本的`face'属性，这会让Emacs将其后的文本用该样式来显示。

   通常情况下，样式通过样式名来引用，样式名是一个与样式属性绑定在一起的Lisp符号。样式名通过`defface'进行定义。

   Emacs在许多地方只接受样式名，而不接受匿名样式。比如 Attribute Functions，和`font-lock-keywords'变量。

   为向后兼容，你也可以用一个字符串来设置样式名，这和Lisp符号是等效的。

*** 样式属性

    样式属性决定了样式的显示效果，下表列出了所有的样式属性，及它们的值和效果。

    除开下面给出的值以外，每个样式属性都可以设置成`unspecified'。这个特殊值的意思是新式没有直接设置该属性，让Emacs参照其父样式或者其子样式执行。`default'样式必须明确设置所有的属性。

    有些属性只在特殊情况下有作用，如果不能处理它，则会被忽略。

    `:family' 字体
    `:foundry'
    `:width'  相对于字符宽度。其值应该是以下这些符号中的一个：`ultra-condensed', `extra-condensed', `condensed',
     `semi-condensed', `normal', `semi-expanded', `expanded',
     `extra-expanded', or `ultra-expanded'.
    `:height' 字的高度，最简单的情况是以1/10点为单位的整数。
    `:weight' 字的大小，其值应该是以下这些符号中的一个：`ultra-bold', `extra-bold', `bold', `semi-bold', `normal',
     `semi-light', `light', `extra-light', or `ultra-light'. 
    `:slant' 字体倾斜，其值应该是以下符号中的一个：`italic', `oblique', `normal',
     `reverse-italic', or `reverse-oblique'。
    `:foreground' 前景色，一个字符串。其值可能是系统定义的颜色名，或者十六进制代表的颜色。
    `:background' 背景色，一个字符串。
    `:underline' 下划线。当其值为nil时，无下划线；当为t时，用前景色添加下划线；当为COLOR时，用指定的颜色添加下划线；当其值为(:color COLOR :style STYLE)时，用指定的颜色和样式。
    `:overline' 上划线，如果其值是t，用样式的前景色；如果其值为字符串，则用字符串指定的颜色；如果其值为nil，则不划线。
    `:strike-through' 删除线，其用法同overline。
    `:box' 方框，如为nil，则无方框；如果为t，则用宽度为1的线、前景色画方框；如果为COLOR，则用宽度为1，COLOR颜色的线画方框；如果为(:line-width WIDTH :color COLOR :style STYLE)，则用指定的样式画方框，WIDTH默认值为1，若其值为-N，意思是说用宽度为N的线在方本下方的空白处画线，而不会增加字符的宽和高。COLOR指定画框的颜色，默认情况下，对于简单的框，使用样式的前景色，对于3D框，还会用到背景色。STYLE指明是否需要画3D的框，如果其值为`released-button'，画出的框看起来像未被按下的按钮，如果其值为`pressed-button'，画出的框像按下的按钮，如果忽略它的值或者设为nil，则画一个普通的平面框。
    `:inverse-video' 倒转视频。其值应该为t和nil中的一个。
    `:stipple' 点画背景，位图。其值可能是包含X位图数据文件的文件名。该文件被查找的路径由变量`x-bitmap-file-path'指定。stipple的值也可以直接指定位图数据，其格式为`(WIDTH HEIGHT DATA)，WIDTH和HEIGHT设置像素的宽度，DATA是包含位置像素数据的字符串，从行到列排列。每行占用(WIDTH+7)/8个连续的字节，也就是说每行至少占用1个整字节。如果stipple的值为nil，则无背景图。通常情况下，你不需要设置stipple属性，因为他自动处理灰度阴影。
    `:font' 字体。其值应该为字体对象。当用`set-face-attribute'
给其赋值时，你还需要提供字体说明、字体实例，或者一个字符串。Emacs会将这样的数值转换成合适的字体对象，并将其存储为实际的font属性值。如果你用字符串，则应该是字体名；如果字体名是XLFD并包含通配符，Emacs会选择第一个与之匹配的字体。要注意的是给这个属性赋值会同时改变 `:family', `:foundry', `:width', `:height',
     `:weight', and `:slant'这些变量的值。
    `:inherit' 父样式的名字，也可以是样式名串。从父样式继承的样式会作为基本样式。如果是样式名列表，则排在前面的样式会覆盖其后的样式。

    函数： font-family-list &optional frame
    返回值为字体簇的名字列表。FRAME设置要进行显示的frame，如果为nil，则使用处于选择状态的frame。

    用户设置： underline-minimum-offset
    用像素值设置基线和下划线之间的最小距离。

    用户设置： x-bitmap-file-path
    给`:stipple'属性提供搜寻文件的目录列表。

    函数： bitmap-spec-p object
    如果OBJECT是用于`:stipple'的合法的位图数据，则返回t，否则返回nil。

*** 定义样式

    宏： defface face spec doc [keyword value]...
    此宏定义新的样式FACE，所有的默认值由SPEC指定。还要将FACE引起来，并且不要以`-face'结束，DOC是该样式的说明文档，附加的KEYWORD的意义同`defgroup'和`defcustom'。
    当此宏运行时，它会用SPEC定义一个新样式，同时从init文件中读入自定义样式对其进行覆盖。
    当你在Emacs Lisp模式中用`C-M-x‘来运行此宏，其结果会覆盖所有自定义的样式。
    SPEC参数是样式说明，针对不同的终端有不同的显示说明。其形式是：
    (DISPLAY . PLIST)
    DISPLAY 指明终端种类，PLIST是样式属性列表。为了向后兼容，SPEC也可以用如下形式`(DISPLAY PLIST)。

    DISPLAY的可能值有：
    `default' 此元素不和任何终端匹配，但是它指定的是所有终端的默认值，如果使用default，则应该是SPEC的第一个元素。所有接在其后的元素都可将其覆盖。
    `t' 此元素则匹配所有的终端，因此所有接在其后的元素均不会被使用。此元素应该是列表的最后一个元素。
    a list 如果DISPLAY是列表的话，应该使用如下形式：`(CHARACTERISTIC VALUE...)。

*** 样式属性函数

函数： set-face-attribute face frame &rest arguments
通过此种方式设置的样式属性会覆盖掉所有用defface定义的样式。
ARGUMENTS 定义要设置的属性和它们的值。示例如下：
#+BEGIN_SRC elisp
(set-face-attribute 'foo nil
                    :width 'extended
                    :weight 'bold)
#+END_SRC
如果FRAME的值为t，该函数设置新frame的样式默认值，如果FRAME的值为nil，则样式影响已经存在的frames和新frames。

函数： face-attribute face attribute &optional frame inherit
函数返回指定或者当前frame上应用的FACE样式的属性值。如果你没有用 set-face-attribute 设置过，则返回值为nil。

*** 样式显示

    Emacs在显示文本的时候遇到多种对显示效果的定义时是这样处置的。
    - 如果文本包含glyph，由glyph定义新样式。
    - 如果文本位于活动区域内，则用`region‘样式。
    - 如果文本位于有意义的叠加中，则用叠加定义的样式；如果叠加中有`mouse-face'属性，并且鼠标处于相当近的位置，Emacs会用`mouse-face'显示文本。
      如果同一字符上定义了多个叠加，则高优先权的覆盖低优先权的。
    - 如果文本包含了`face'和`mouse-face'属性，则用这些属性。
    - 如果文本位于模式行中，用`mode-line'样式。在首行中，则用`header-line'样式。
    - 如果没有设置任何属性，则用默认的样式。
      
      在任何阶段，如果样式的`:inherit'属性是合法的，则将当前样式中值为`unspecified'的属性从父样式中拷贝。若其父样式中的此属性值亦为`unspecified'则继续往上追溯。

*** 样式重映射

    变量： face-remapping-alist
    变量是一个嵌套列表，它的元素形式为`(FACE .REMAPPING)。它让Emacs用REMAPPING样式来显示原来指定用FACE样式进行显示的文本。
    如果`face-remapping-alist'是一个局部变量的话，其只作用于与其绑定的buffer。

    *注意* 样式重映射不会递归。

   下面有一些高层的设置 face-remapping-alist 变量的接口函数。推荐用这些函数来修改此变量，而不是手动直接修改它。这些函数只会把 face-remapping-alist 当作局部变量来对待。并且总是使用如下的结构来处理此变量。

   （FACE RELATIVE-SPEC-1 RELATIVE-SPEC-2 ... BASE-SPEC）

   如上所述，每个 RELATIVE-SPEC-N 要么是样式名，要么是一个由“属性/值”对构成的列表。 RELATIVE-SPEC-N 由函数 `face-remap-add-relative' 和函数 `face-remap-remove-relative' 来管理，而 BASE-SPEC 的优先级最低，由函数 `face-remap-set-base' 和函数 `face-remap-set-base' 来管理。

   函数： face-remap-add-relative face &rest specs
   该函数将FACE中定义的属性映射成SPECS中定义的样子。其返回值是一个Lisp 对象，你可以将其传递给 face-remap-remove-relative 来删除映射关系。

   #+BEGIN_SRC elisp
          ;; 将 `escape-glyph' 样式映射成由
          ;; `highlight' 和 `italic' 定义的新样式:
          (face-remap-add-relative 'escape-glyph 'highlight 'italic)

          ;; 修改 `default' 样式中高度为 150%:
          (face-remap-add-relative 'default :height 1.5)
   #+END_SRC

*** 样式自动应用

    这个钩子是自动在buffer中的文本上应用样式的，它是Jit-Lock模式的部分实现，在Font-Lock里面用到。
    变量： fontification-functions
    这个变量是Emacs在重绘时要调用的函数的容器，但是在重绘前调用。即使 Font Lock 模式没有被激活，它们也会被调用的。当 Font Lock 模式被激活时，这个变量里面通常只有一个函数： `jit-lock-function'。
    变量里面的函数会被依次调用，只有一个参数： buffer里面的位置POS。也就是从POS开始应用样式。
    该函数应该在 face 属性中记录 buffer 中应用的样式名。同时还要给添加了样式的文本的`fontified'属性设置一个非空的值，以告知重绘程序样式被应用到这些文本上了。
    如果在POS之后的某些文本上已经有非空的`fontified'属性，最好不要去动它们，但这不是必须的，只是会将前面的设置覆盖掉。
    为效率着想，建议每次调用函数只对400至600个字符应用样式。

*** 基本样式
    如果你想在文本上应用样式，建议用原来已有的样式或者是从已有的样式上继承来定义新的样式，而不是定义一个全新的样式。这样的话，如果其他用户已经给Emacs定义了一个样式，你的程序会使用他，而不需要重新自定义。
    下面是一些Emacs里面定义的基本样式，你可能想用 Font Lock 样式来达到语法高亮。
    `default' 默认样式，它的所有的属性值都有明确的设置。其他的样式直接或者间接地继承于它。
    `bold'
    `italic'
    `bold-italic'
    `underline'
    `fixed-pitch'
    `variable-pitch'
    上面这6个样式只设置了以它们的名字命名的属性，其他的属性全部是`unspecified'。
    `shadow' 针对无效的文本。比如，在minibuffer中在文件名中不关心的部分用些样式。
    `link'
    `link-visited'
    上面这2个样式针对可以点击的文本按钮，可以定位至buffer中其他地方。
    `highlight' 针对那些需要临时放大以引人注目的文本。比如在`mouse-face'中做到鼠标高亮。
    `match' 针对与搜索命令匹配的文本。
    `error'
    `warning'
    `success'
    以上3个模式针对那些关心错误、警告和成功的文本。比如这些样式用在`*Compilation*' buffer中的消息文本上。
    
*** 字体选择
    当Emacs在图形显示器上绘制字符之前，它必须选择一种字体。通常Emacs选择针对当前字符的样式中`:family'、`:weight'、`:slant'和`:width'属性设置的字体。同时显示的效果也取决于要显示的字符，因为有些字体只包含一小部分字符。如果没有字体满足要求，Emacs会使用与之最近似匹配的字体。下面的这些变量控制Emacs如何选择字体：

    用户设置： face-font-family-alternatives
    如果样式中设置的字体不存在，用这个变量中设置的字体进行尝试。变量中的每个元素应该具有以下的形式：
    (FAMILY ALTERNATE-FAMILIES...)
    如果样式中的FAMILY不可用，则尝试 ALTERNATE-FAMILIES 中给出的字体，直到找到一个存在的字体。

    用户设置： face-font-selection-order
    如果没有字体满足样式中的所有属性： (`:width', `:height', `:weight', and `:slant')，则由这个变量决定这些属性被满足的优先顺序。变量的值是包含前面这4个属性符号的列表。默认情况下是： `(:width :height :weight
     :slant)'。

    用户设置： face-font-registry-alternatives
    在设置的registry不存在的情况下，该变量让Emacs尝试其他的registries。变量中的每个元素应该是如下形式：
    (REGISTRY ALTERNATE-REGISTRIES...)
    Emacs会尝试 ALTERNATE-REGISTRIES 中的条目，直到找到为至。

    Emacs可以使用可变字体，但是默认情况下它不会使用。
    用户设置： scalable-fonts-allowed
    这个变量指定Emacs可以使用的可变字体。默认情况下其值为nil，意思是不使用可变字体，如果是t，则可以使用任何可变字体。否则，其值必须是一个列表。然后，如果某个可变字体与列表中的表达式相匹配的话，Emacs会使用它。例如：
    (setq scalable-fonts-allowed '("muleindian-2$"))
    允许Emacs使用注册为 `muleindian-2$' 的可变字体。

    变量： face-font-rescale-alist
    该变量设置样式的缩放系数。其值应该是下面这种形式的集合。
    (FONTNAME-REGEXP . SCALE-FACTOR)
    如果FONTNAME-REGEXP 与将要使用的字体相匹配的话，则根据 SCALE-FACTOR 选择一个更大的相似的字体。当某些字体比通常的要大或者要小的时候，你可以使用这个变量来改变它看起来的大小。

*** 字体集
     字体集是不同范围编码的字体的集合。一个单独的字体不能满足所有Emacs支持的显示所有字符的需要，但是字体集可以。字体集像字体一样有它的名字，在为frame或者face设置字体的时候，你同样可以使用字体集。下面是在Lisp程序中定义字体集的方法。

     函数： create-fontset-from-fontset-spec fontset-spec &optional style-variant-p noerror
     函数根据说明字符串 FONTSET-SPEC 定义一个新的字体集， FONTSET-SPEC  应该具有下列形式：

     FONTPATTERN,[CHARSET:FONT]...
     在逗号前后的空格会被忽略。

     FONTPATTERN应该是标准X字体名字，CHARSET和FONT应该是`fontset-ALIAS'。

** 窗口边框

在图形显示中，Emacs在每个窗口的两边显示边框，在其中显示位图来表示行截断、行延续、水平滚动等等。

*** 边缘大小和位置

    以下这些局部变量控制显示buffer的窗口边框的位置和宽度。

    变量： fringes-outside-margins
    边框通常情况下出现在显示边缘和窗口文字之间，如果其值不是nil，它们出现在显示区域的外面。

    变量： left-fringe-width
    如果值不是nil，该值为左边框的像素宽度，如果其值为nil，左边框的宽度应该和窗口的frame相同。

    变量： right-fringe-width
    如果值不是nil，该值为右边框的像素宽度，如果其值为nil，右边框的宽度应该和窗口的frame相同。

    如果buffer不设置这些变量的话，Emacs将使用frame参数：`left-fringe'和`right-fringe'来绘制窗口的边框。

    上面这些变量在`set-window-buffer'函数中才会真正起作用，这个函数会调用`set-window-fringes'。如果你更改了这些变量中的一个，边框的显示不会立即刷新，除非你调用`set-window-buffer'，此时所有的窗口都会受到影响，当然，你也可以在单独的窗口中调用`set-window-fringes'。

    函数： set-window-fringes window left &optional right outside-margins
    这个函数设置窗口WINDOW的宽度，如果WINDOW的值是nil，则作用于当前窗口。
    LEFT参数设置左边框的像素，RIGHT设置右边框的像素。如果为nil，则用默认值。如果 OUTSIDE-MARGINS不是nil，意思是说边框应该显示在显示边缘的外面。

    函数： window-fringes &optional window
    该函数返回窗口WINDOW的边框信息，如果WINDOW值为nil，则作用于当前窗口。取得的值的形式是：`(LEFT-WIDTH RIGHT-WIDTH OUTSIDE-MARGINS)'。

** 滚动条
   通常情况下，frame参数`vertical-scroll-bars'决定窗口是否有垂直滚动条，垂直滚动条是在左边还是右边。frame参数`scroll-bar-width'则控制滚动条的宽度。

   函数： frame-current-scroll-bars &optional frame
   该函数返回FRAME的滚动条设置，返回值的形式是`(VERTICAL-TYPE . HORIZONTAL-TYPE)'，其中 VERTICAL-TYPE 的值是 `left'、`right'、和nil中的一个， HORIZONTAL-TYPE 用来设置水平滚动条的类型，但是因为还没有实现，所以其值始终是nil。
   你可以通过修改`vertical-scroll-bars'变量来显示或者隐藏特定buffer的滚动条，该变量自动转化为局部变量。可能的值为`left'、`right'、`t'和`nil'，其中，t代表用frame的设置，nil代表不要滚动条。

   你也可以通过调用 `set-window-scroll-bars' 来为设置单独窗口的滚动条。

** 显示属性
   文本或者叠加的display属性用来在文本中插入图像，并且控制文字的显示效果。`display'属性的值是一个显示说明字串，或者包含多个显示设置的列表及向量。在同一个`display'属性中的多个显示设置同时作用于文字对象上。

   如果文本上有多个显示说明（叠加和文本属性），其中只有一个起作用，请查看`get-char-property'以了解更多。

*** 文本替换显示
    某些显示说明要在具有显示属性的文本中显示内容，这被叫作替换显示。Emacs不允许用户将插入点移动至已经被替换掉的文本中间。

*** 指定空白
    
** 图片显示

   要在Emacs中显示图片，首先需要创建一个图像描述符，然后在`display'中作为显示说明使用。

   Emacs只会在图形显示器上才能显示图像，在文本终端上不能显示图像，在一些不支持显示图像的图形终端上以及编译Emacs没有加入图像支持时，也不能显示图像。你可以使用`display-images-p'函数来查看原则上图像是否被支持。

** 按钮

按钮库定义了许多函数用于插入和维护可以响应鼠标和键盘的按钮。这些按钮的典型应用提各种超链接。

按钮本质上来说是一些文本或者叠加属性的集合绑定在buffer中的一断文字上。这些属性被称作“按钮”属性。属性之一，"action property"，设定了一个在用户用鼠标和键盘触发按钮的后被调用的函数。如果需要的话，动作函数可以检查按钮并使用其属性。

在某种意义上，按钮库复制了Wideget库的功能。其优点是，更快、更小、更简单。从用户的角度看，这两个库的提供的接口是非常相像的。

** 抽象显示

   Ewoc 库构造用

   ewoc 是一个用于结构
   ewoc 的buffer中的内容分为三部分，按顺序是：首先是固定的“header”，然后是一系列的数据元素的文本描述，最后是固定的“footer”。具体地说，ewoc包括以下这些信息：
   - 一个buffer
   - 在buffer中的起始位置
   - 头部和脚部字串
   - 节点组成的双头链，每个节点包含内容有
     - 数据元，是一个Lisp对象
     - 向前和向后的联结
   - 一个用于在buffer中插入展示数据的文本的“类打印机”。

典型作法是用`ewoc-create'来定义ewoc，然后将创建的结果传递给Ewoc库里面的其他函数，最后在buffer中展示结果。一旦结果展示在buffer中之后，其他函数检查buffer中的位置和节点，在结节中移动等等。

节点包装了数据就像变量一样。通常包装操作发生在将节点添加至ewoc的时候，你可以从节点中取回数据然后放一新的数据进去。像这样：

(ewoc-data NODE)
=>value

(ewoc-set-data NODE NEW-VALUE)
=>new-value

你也可以用Lisp对象或者索引号。

当数据改变时，你肯定想更新buffer中的文字，你可以使用`ewoc-refresh'来更新所有的节点，或者用`ewoc-invalidate'来改变节点，或者用`ewoc-map'带上参数来更新所有节点。同时你可以用`ewoc-delete'或者`ewoc-filter'来删除失效的节点。当删除节点的时候，同时也会从buffer中删除它的文本描述。

** 括号闪烁

   这节讲述的是Emacs是怎样实现在用户输入圆括号后进行闪烁的。

   变量： blink-paren-function
   变量的值是一个在输入成对字符的后半部分后要调用的函数。其值也可以是nil，意思是什么事也不用干。

   用户设置： blink-matching-paren
   如果其值为nil，则`blink-matching-open'什么也不会干。

   用户设置： blink-matching-paren-distance
   这个变量设置的是搜寻配对后括号的最远距离。

   用户设置： blink-matching-delay
   这个变量设置的是光标停留在与之配对的括号上面的时间。小于1秒时间看起来效果最好，但是在所有系统上的默认时间是1秒。

   命令： blink-matching-open
   这个函数是`blink-paren-function'的默认值。它假设输入的字符是前面某个符号的配对，并将光标移动到与之配对的字符上并停留一小会儿。如果其该字符要配对的字符不在屏幕上，则将其显示在回显区内。为了避免较长的延时，此函数搜索的距离不会超过`blink-matching-paren-distance'定义的距离。

   下面是一个明确调用此函数的倒子：

   #+BEGIN_SRC  elisp
           (defun interactive-blink-matching-open ()
            "Indicate momentarily the start of sexp before point."
            (interactive)
            (let ((blink-matching-paren-distance
                   (buffer-size))
                  (blink-matching-paren t))
              (blink-matching-open)))
   #+END_SRC

** 字符显示
   这一节讲述的是字符实际上是怎么显示出来的。通常，一个字符是作为一个“glyph”（在屏幕上占用一个字符宽度的图形符号）来进行显示的，它的表现形式决定于字符本身。例如：字符`a'显示出来也是`a'，但是有些字符显示出来就比较特别。例如： 格式字符（编码为12）被显示成两个图符的序列，`^L'，而换行符则开始一个新行。

   你可以通过修改“display table”（显示映射表）来控制每个字符显示出来的样子，这张表将每个字符编码映射成图符序列。

*** 常规显示

    下面是在没有显示映射表的情况下显示字符编码的约定。
    - 可打印的ASSII字符，按原样输出。
    - TAB控制符显示成具有tab长度的空格。变量`tab-width'控制每个tab字符占的空格的个数。
    - 新行符结束前面的行并开始新的一行。
    - 不可打印的ASSII控制符显示方式由变量`ctl-arrow'定义的两种方式中的一种决定。如果该变量的值不为nil，这些控制符就显示为两个图符的序列，其中第一个图符是`^'。例如：<DEL>字符显示成`^?'。
      如果 `ctl-arrow'的值是nil，这些控制符显示成八进制转义序列。
      
      这条规则同样同样适用于回车符（字符编码为13），但是回车符通常不显示在buffer的内容中，它被作为行尾转换符而忽略掉了。
    - 原始字节不是ASCII字符，这些字符显示成八进制转义序列，由四个图符组成。第一个图符是`\'，其他图符是字符的八进制编码。
    - 任何编码大于255的非ASCII字符，如果终端支持的话，按字符的原样显示。如果终端不支持，这些字符被称作非图符，通常用占位符在Emacs中显示。例如，如果图形终端没有字符的字体，Emacs通常显示一个包含有该字符的十六进制数的小方框。
      

上面这些显示约定在具有显示映射表，但有些字符在显示映射表中的条目为nil时仍然适用。所以，当你在编写显示映射表的时候，你可以只定义那些特别表现的字符。

下面这些变量决定某些字符在屏幕上如何显示。因为它们改变了字符占用的列宽，它们同样会影响用于缩进的函数、模式行的显示。如果你想用新的值强制重绘模式行，只要调用`force-mode-line-update'就行了。

用户设置： ctl-arrow
如果其值不是nil，控制符被显示成脱字符加一个字符的样子，如果其值为nil，则被显示成八进制转义序列。

用户设置： tab-width
这个变量的值是每两个tab停止点在Emacs中显示的空格数。单位是列，默认为8列。 *注意* 这个特征与`tab-to-tab-stop'命令使用的user-settable中的tab符互不影响。

*** 显示映射表
    显示映射表是一个用于特殊目的的字符表，用于覆盖字符的常规显示约定。这节讲述怎样制作、检查显示映射表，如何给显示映射表赋值。

    函数： make-display-table
    创建并返回一个显示映射表，表中所有元素的初始值均为nil。

    显示映射表上的普通元素是在索引字符编码；在C索引位置上的字符表示如何显示编码为C的字符。元素的值要么是nil，要么是图符向量。

    *警告* 如果你用显示列表来修改换行符的显示图符，整个buffer会被显示成一个整行。

    显示映射表还有六个可用于特殊目的的保留位置。下面是这些位置的意义，如果位置上的值为nil，则用下面说的默认效果。
    0 屏幕上用于表示截行的的图符，默认为`$'。在图形终端上，Emacs在边框上用箭头来表示截行，此时显示映射表没有意义。
    1 屏幕上用于表示续行的的图符，默认为`\'。在图形终端上，Emacs在边框上用弯箭头表示续行，此时显示映射表没有意义。
    2 用于表示跟在其后的是八进制数字的图符，默认是`\'。
    3 用于表示跟在其后的是控制符的图符，默认是`^'。
    4 用于表示其后存在不可见行的图符，默认是`...'。
    5 用于表示窗口边界的图符，默认是`|'。

    下面是在显示映射表中设置`ctl-arrow'为non-`nil'的例子。
    #+BEGIN_SRC elisp
     (setq disptab (make-display-table))
     (dotimes (i 32)
       (or (= i ?\t)
           (= i ?\n)
           (aset disptab i
                 (vector (make-glyph-code ?^ 'escape-glyph)
                         (make-glyph-code (+ i 64) 'escape-glyph)))))
     (aset disptab 127
           (vector (make-glyph-code ?^ 'escape-glyph)
                   (make-glyph-code ?? 'escape-glyph)))
    #+END_SRC

    函数： display-table-slot display-table slot
    此函数返回DISPLAY-TABLE中的SLOT。参数SLOT是0到5间的数字，或者是槽名。即`truncation', `wrap', `escape', `control', `selective-display',和 `vertical-border'之一。

    函数： set-display-table-slot display-table slot value
    此函数用于修改指定的DISPLAY-TABLE中特定SLOT的值。SLOT的取值同函数`display-table-slot'。

    函数： describe-display-table display-table
    函数返回关于显示映射表DISPLAY-TABLE的描述。

    命令： describe-current-display-table
    在help buffer中显示当前显示映射表的相关信息。

*** 激活显示映射表
    每个窗口或者buffer可以绑定一个显示映射表。窗口显示映射表的优先级高于buffer。如果两个表均不存在的话，Emacs会使用标准显示映射表，如果其中的元素为nil，则使用字符的常规显示约定。

    要注意的是，显示映射表会影响到模式行的显示，如果你想要强制重绘模式行的话，调用函数`force-mode-line-update'。

    函数： window-display-table &optional window
    返回窗口 WINDOW 的显示映射表，如果未设置则返回nil。

    函数： set-window-display-table window table
    把表格TABLE设置为窗口WINDOW的显示映射表。

    变量： buffer-display-table
    其值为buffer的显示映射表。如果为nil则没有设置。

    变量： standard-display-table
    其值为标准显示映射表，Emacs在找不到窗口显示映射表又找不到buffer显示映射表的时候会使用它。默认值为nil。

    `disp-table'库定义了许多的函数为修改标准的显示映射表。
    
*** 图符
    图符是一个图形符号，在屏幕上占用一个字符的宽度。每个图符在Lisp中用一个图符编码来表示，图符编码由一个字符和可选的样式组成。下面这些函数用来维护图符编码：

    函数： make-glyph-code char &optional face
    CHAR是图符编码中的显示字符，FACE是图符编成中的样式，样式可以设置成nil
    
    函数： glyph-char glyph
    此函数返回图符编码GLYPH中的显示字符。

    函数： glyph-face glyph
    此函数返回图符编码GLYPH中的样式，如果为空，则表示使用默认的样式。

你可以修改图符映射表来控制图符在如何在文本终端上显示的。但此特征要过时了，推荐用`glyphless-char-display'。  
    
** 声音
   这一节讲述的是Emacs是怎样用摇铃或者闪烁来引起用户注意的。使用声音要保守，频繁的响铃也会让人厌烦。不要在出错的时候总是用响铃是较为恰当。

   函数： ding &optional do-not-terminate
   此函数开启响铃或者闪烁屏幕。除非将DO-NOT-TERMINATE设置成non-nil，否则它会中断所有在运行中的键盘宏。

   函数： beep &optional do-not-terminate
   它是ding的近义词。

   用户设置： visible-bell
   这个变量告诉Emacs在响铃时要不要闪屏。nil意为否，其他意为是。这在图形显示终端上是有效的，在字符终端上使用Termcap软件包来定义可视响铃功能。

   变量： ring-bell-function
   如果其值不是nil，则应试是一个没有参数的函数，告诉Emacs该如何摇铃，并且其优先级要高于`visible-bell'。

** 窗口系统

   Emacs 能和许多的窗口系统进行配合，特别是X窗口系统。Emacs和X都使用“窗口”这个词，但是意义不同。Emacs中的frame才X中认为的单个窗口，而Emacs中的窗口在X中没有定义。

   变量： window-system
   此变量告诉Lisp程序Emacs正在用于显示frame的窗口系统。可能的值有：
   `x'
   `w32' MS-Windows GUI.
   `ns' Nextstep interface.(在GNUstep和苹果系统上使用)
   `pc' MS-DOS
   `nil' 字符终端

   变量： initial-window-system
   此变量中的值和`window-system'中的一样，用在Emacs启动过程中创建第一个Frame。

   函数： window-system &optional frame
   返回当前frame，或者指定的frame中基于的窗口系统。其值的意义同上面介绍的`window-system'变量的值。

   如果你想针对图形显示终端和字符显示终端写不同的代码，不要将 `window-system'和`initial-window-system' 作为谓语或者布尔变量。因为`window-system'不是一个Emacs运行系统的良好指示器。你应该用`display-graphic-p'或者其他`display-*-p'谓语。

   变量： window-setup-hook
   该变量是Emacs在处理完配置文件后运行的常规钩子。

   该钩子用于内部目的：配置与窗口系统之间的通信，创建初始窗口。用户不要干涉它。

** 双向显示

   Emacs 可以显示脚本文件，比如Arabic,Farsi和Hebrew，这些语言水平书写方向是从右向左。更是有，嵌入在从右向左的语言中的拉丁语和数字片断是从左向右显示的，相反方向的例子也一样。