#+title:人生的智慧(The wisdom of life)学习笔记

至亲之人患上了难治之病，个人职业遇到了瓶颈，小孩上学地又要面临选择，感觉人生到了
一个关键的十字路口，需要自己做决策的事项都涌了上来，突然很迷茫。人生太复杂，快到
四十的人仍然做不到不惑，于是买了《人生的智慧》（叔本华）《幸福之路》（罗素）《病
隙碎笔》（史铁生）这几本书来读，试图找到答案。这里是《人生的智慧》学习笔记。

* 基本划分

这本书是叔本华所著，总体上看逻辑还是比较缜密的，从人的自我、人的所有、人在他人眼
中的样子三个方面进行了详细的阐述。

*人的自我* 即在最广泛意义上属于人的人格的东西。因此，它包括人的健康、能力、外貌、
气质、道德品格、智力及其教养。

*人的所有* 亦即财产和其他意义上的占有物。

*人的显现* 即人在他人眼中所显现的样子，也就是人们对他的看法。产生了荣誉、地位、
名声。

"我们幸福的原因在于我们自身之内，而非自身之外。" -- 伊壁鸠鲁的第一个门徒门采多鲁
斯。

大叔在第一章阶段的划分中贯彻了他表象和意志本体的观点，指出人的自我是主体，性格、
精神能力、健康等自身的价值是绝对的，决定幸福。即只有通过最大限度地发挥我们既定的
个性，选择适合自己性格的职业和生活方式才能接近幸福。

大叔赞同一定财富对幸福生活的重要性，三种划分之间的重要性是依次递减的。“第二项与
第三项有一种人尽皆知的关系。彼德尼斯说得很对：如果你拥有某种东西，那么别人将视你
与此东西等价。反过来年，他人以任何形式对我们所做出的评价，都将有助于我们获得财富”

不知道是不是翻译的问题，这本书有的地方的论述总感觉有些牵强，有的地方又前后矛盾。
比如：”当下现实的客体这一半掌握在命运的手里，因此是可以改变的；而主体这一半是我
们自身，所以，就其本质而言，它是不可改变的。”前半句说命运是可以改变的，而本书的
后半部分有论述说要屈从于命运、不要抗争；而说自身不可改变，但在分类的阐述中又说人
的自我包括健康、能力、外貌等等，明显这些中的部分是可以改变的，从下文中看，他想说
的的性格和精神能力（我理解是智力）。不管怎样，这些矛盾和冲突让这本书看起来并不严
谨。知乎上有人问，说看不懂叔本华的《人生的智慧》，回答的人说那应该怀疑读者的水平，
而不是作者的问题，但就这种还没有深入到所谓意志和表象上的看不懂怕不是读者的问题吧。

* 人的自我

大叔说：身心和谐健康是第一位的，也是最重要的。乐观的性格对幸福最有直接帮助，通过
乐观收获的快乐是幸福的钞票。最有利于乐观的是健康，是无助于乐观的是钱财。为了保持
健康，则要运动，因为”生命在于运动”。

使我们幸福或者不幸的，不是客观的现实事物，而是我们看待他们的方式。

"虽然开朗的性格对健康的贡献是根本性的，但后者并非完全依靠前者：因为即使一个人完
全健康，他也可能性情忧郁、终日消沉"。

人类幸福的两个敌人：苦难与无聊。（罗素幸福之路着重讨论的是无聊，他是有意忽略了外
在的影响。）苦难是外在而客观的，而无聊是内在而主观的。也就是说，困境与贫穷产生痛
苦，相反，安逸与富余产生无聊。（这样的论证比罗素更全面。）无聊需要刺激，总之不能
让脑袋闲下来想东想西，而苦难则是治疗无聊的良药。这其中的平衡点就是幸福。

_庸俗的人仅仅考虑如何消磨时间，而怀才在身之人则考虑如何利用时间。_
_亚里士多德：“幸福属于自足者。”_

大叔是多么骄傲的一个人啊，看不起黑格尔，也看不起歌德。他说歌德为了谋取荣耀、地位、
豪华、头衔与名声，将自己的安宁、悠闲与独立大把葬送。

叔本华提出的三种享乐：首先是人类新陈代谢的能力所带来的乐趣，它包括饮食、消化、休
息和睡觉。其次是发挥体力所带来的乐趣，它包括散步、跳跃、摔跤、跳舞、击剑、骑马以
及类似的体育活动。第三类是心灵感受的乐趣，它包括观察、思考、体验、赏诗、绘画、奏
乐、学习、阅读、冥想、发明、哲思等。

大叔说：人们为了应付无聊，偶尔会以琐碎而随便的动机为借口去刺激意志，而意志进而奴
役智力，并将智力所想之事付诸实践。他口中刺激是相当狭隘了，好像只有赌博和打牌一样，
都是邪恶而后患无穷的活动。他始终在强调拥有卓越精神能力的人——当然他自己肯定是其中
之一——才能发现和感受到高尚的快乐。他提出通过学习、观察、研究、冥想、实践才能做到
这些（从这里看起来精神能力好像也不是智力，不知道是个什么能力，但至少看出他也是承
认人的自我是可以改变的吧，并不同于他在前文中所表述的那样难以改变。）

_古往今来，每个伟大精神人物莫不将自由闲暇奉为至高无上的价值。_ 对于伟大的人物来
说，闲暇不会无聊，而是他自我提升的大好时机，这也是他们的快乐源泉。对于平庸的人来
说，不太可能有闲暇，即使有，也极易演变为无聊。

大叔认为”菲利斯特人”（庸人）没有精神需求，只有生理需求，他不寻找精神需求，而只
寻找那完全肤浅的快乐。从这里可以看出，他认为人生的智慧是如何获取精神上的富足和愉
悦。

* 人的所有
伊壁鸠鲁将人类的需求划分为三类：
1. 自然且必要的需求，只有饮食和衣物属于这类需求。
2. 自然且不必要的需求，它就是满足性欲的需求。
3. 既非自然又非必要的需求，就是对奢侈、铺张、炫富和浮华的需求。

财富的多少与幸福并不成正比，关键看人的期望是多少，不需要财富的人，即使没有它，照
样怡然自得，富有的人需要更多的财富而不得同样会很痛苦。获得钱财后关键看如何进行经
营，普通人（非商人）要多存少花，以防江郎才尽。

叔本华说的穷人在得到财富后容易用来享乐和挥霍并不是普遍真理。他亦认为有祖传家业的
人非常幸运，可以为自己的才华而活。而要想加官晋爵的人带着财富来世学不会处世之道，
反而不利。

* 人在他人眼中的样子

人的价值有两种，一是人们自身并为了自身的价值，另一个是人们纯粹在他人眼中的价值。
这第二种价值被别人的意识所决定，对我们的影响是间接的，只有在别人的意识对某个东西
的影响间接影响到我们自己时才值得我们去考虑。所以，我们最好在我们自身和我们的所有
中去寻找幸福。

这里感觉叔本华好恐怖，他将荣誉连同威望和地位批判得淋漓尽致。由于我们太过重视这些，
才为那些想控制人，乃至驾驭人的人提供了一个合适的理由。军人、医生、法官、教师等职
业的荣誉莫不有此意思。如果不在意别人的想法，集体能不能得到约束？中国古话有讲，树
活一张皮，人活一张脸，可见对名声、荣誉的重视。荣誉是有利可图的，比如别人的尊重，
社会的便利等。爱尔维修《论精神》：”我们喜爱荣誉并非为了荣誉本身，而只是想得到它
带给我们的好处”。

荣誉，从客观上来说，是别人对我们的价值的评价；从主观上来说，是我们对这种评价的畏
惧。 只有看重它，才会有积极的作用。

没有什么东西，比对获得或重提别人的好评的依靠，更能增强一个人的生活通气。因为别人
的好评向他许诺，所有人的力量会联合起来，形成保护和帮助，这个力量与他自身相比，是
一个坚不可摧的防护墙，足以对抗生活的不幸。

好胜、虚荣和骄傲是本性中的愚蠢。

勋章是汇票，来自公共的评议，其价值建立在签发人的信用的基础之上。（这两年习近平主
席发过不少勋章。）

英语的“性格”一词，很好地表达了名声、声望、荣誉的意思。

荣誉的最终根据，是对一个人的道德性格的不可改变性的确信，比如，战士的荣誉表名战士
这个主体英勇无畏、骁勇善战等。荣誉的象征首先是头衔和勋章，其次，在更广泛的意义上
来说就是一般阶层荣誉。它纯粹源于人这个主体，基于人的作为和不作为的事情，而不是基
于别人所做的事情和发生在他身上的事情。头衔必须努力争取才得到，而荣誉只要维护不让
它丢失就好。一个人没有头衔，顶多是默默无闻的，消极的；然而，一个人没有荣誉，却是
令人可耻的，是积极的。

普通人并不能像苏格拉底那样在被打了之后还讲“如果一头驴撞了我，我也要控诉它吗？”，
严然中国的阿Q，在力量不及的情况下只是寻找心理上的平衡。究竟是怎样的人才能以平常
之心对待他人的侮辱呢？对抗侮辱，就是适当的报复。

名声和荣誉是双胞胎，名声长生不死，而荣誉终有一死，荣誉要求每个人公开展示自己的素
质，名声则是向他人炫耀自己。别人对我们有多少了解，我们就有多大的荣誉；相反，名声
远远走在别人对我们的了解之前，前且让我们获得相应的荣誉。 

成就名声要么通过丰功伟业，要么通过传世经典，但功业亦转瞬即逝，只有经典才能万古常
昭。（从业十年，反思并没有留下可圈可点可说可道之事迹，无功业、无经典，注定只能是
普通人。此后至身退，因已错过2017年之机会，几乎不再可能建功立业，想著经典亦无此能
力。）

按照叔本华的说法，每个人只能理解并重视与他生命气质相同的东西。他的这本书我好像还
能看懂，而他自己又自称这是伟大的作品，我是应该庆幸自己的聪明呢还是怀疑是否真的懂
了呢？他这样给一个人定性是有失偏颇的，智慧和能力是可能习得的，现在不理解不代表以
后不理解。

就像光如果不被一个物体反射，它本身是不可见的，每一个超凡脱俗的人如果不借助名声，
他就不会为世人所认可。（这让人想起了东晋的隐士，他们常常聚在一起作诗文，莫不是为
了名声。）为博名声而不得，可能是作品确实不行，亦可能是还不被世人发现或者理解。对
于第一种情况，只有用心去打磨自己的作品，对于后一种情况则静静等待。

我们可以把名声比作冬梨，在夏天生长，在冬天的时候就可以享用。一个人，在垂暮之年，
没有什么别的东西足以告慰，只有将他年轻时的全部能力，铸造成一部作品，一部永不会随
着我们老去的作品。（年轻时谈名声还为时过早，只需默默地准备；我们的孩子也是我们的
作品，如果他们能够取得成功，也会为我们博得名声。）

大叔在讨论学科名声的时候，指出了易于成功的途径，对普通学科材料的组合，容易被大众
接受，但要创新就比较困难；而对于人类理智、情感和大自然的力量方面的研究则需要创新
和深入挖掘；对于很难取得的材料，要做出成绩就比较容易。

人们要尽可能地扩展他的视野，甚至对各门学科都要有所涉猎；而不要过分陷入极少数人涉
足的特殊学科中的某个领域，更不要去死抠那些细枝末节的东西。

* 建议和格言

倘若你失去了一个世界，不要为此悲伤，这无关紧要；
倘若你得到了一个世界，不要为此欢喜，这无关紧要；
痛苦与欢乐，瞬息即逝，世界瞬息即逝，这无关紧要。
                                   萨迪《古丽斯塔》

亚里士多德《尼各马可伦理学》：理性的人追求的是免于痛苦，而非寻欢作乐。这教导我们，
不要把注意力放在生活的享乐和安逸上，而是要尽可能致力于远离生活中难以计数的不幸。

人总是更容易记住痛苦或者难过的东西，比如同老婆吵架的时候都只能想起对方一系列的缺
点，而忽视了他们的优点。战胜痛苦后取得的成就才是让人认为值得而快乐的原因。

他反对将享乐与欢愉作为人生的目标，也是有一定道理的。对当下的活动进行考察，享乐与
欢愉对未来没有积极的影响（实质上对于保持自身的健康还是很重要的），而痛苦的过程却
可以期望在未来战胜痛苦时得到精神上的愉悦，我想如果能够保持愉悦的心情来战胜困难，
这是不是就可能形成积极正向的循环，这时已经没有了痛苦，而只胜困难而已。这时乐观的
心态就至为重要了，这有点像罗素的观点。

缓缓的江水不急于向前，但终归要入海。

我认为，叔本华让大家以悲观的心态来对待生活，只是让大家做好心理准备，不至于遇到真
正的不幸时一蹶不振。

然而，究竟什么是幸福呢？随时因悲观心态造成的担忧是幸福？显然不是。万事遂意，心情
舒畅是我理解的幸福。不论是困难也好、享乐也好，我能按照我的心意去克服困难，去达成
享乐，去避开无聊，我就是幸福的。总之，幸福是一种欲望的满足。然社会资源有限，不可
能每个人的每一个欲望都能得到满足，与其让欲望（意志）受挫，还不如理智地对它进行筛
选，将不好的欲望消灭在萌芽状态（甚至它就不会产生）。叔本华说的致力于避开不幸无非
是通过设定生活目标筛选欲望的过程。尽量保证大部分的愿望都能达成，我们也因此获得了
幸福。分析他的三种基本划分，第一项人的自我是最容易改变的（我指的不是性格），基本
上在不需要别人参与只要自己愿意的情况下都是可以改变的，而第二项人的所有则是在我们
努力并且社会配合的情况下可能改变，第三项人在他人眼中的样子是最难改变的，只有通过
改变我们自己才可能达成。于是幸福之路的设定无外乎改变自己的教养、能力、智力等，顺
便增加我们的财富，而尽可能地忽略他人对我们的看法。通过改变自己的精神境界，可能合
理地控制我们的欲望，比如衣食住行够用就行，减少对社会对他人的需求，避免期望受挫，
可以增加幸福感。用现在的话讲，躺平的人就是最易幸福的人。

我的不幸是什么呢？原来老人的赡养、小孩的教育、家人的陪伴这些需求，在降低一点要求
后，比如能够给老人生活费，小孩有书读就行，家人还可以见到，我就没有什么烦恼了。老
婆生病的事，我想为了后续保障，我们已经做了比较合适的选择了。人生后续的路是什么样
的，我们都讲不清楚，只有到眼前了，看到了才能结合当前进行衡量，加强修养、不去攀比、
清心寡欲增强幸福感。这时来想极简主义和犬儒主义也是有些道理的。

想起罗素的《幸福之路》，他在第一章中就很明确地讲，那些难以改变的影响幸福的社会制
度什么的就不讨论了，可见他是看得很透彻的。

大叔说：优秀而高尚的人，会立刻领悟命运的教导，并且会顺从天命，必怀感恩。他们明白，
人生在世不可能寻得幸福，只能领受教诲。（这或许就是这本书为什么叫《人生的智慧》的
原因吧。）

** 我们对自己本身的态度

凡事皆必然，因为我们在每一刻都只做我们那时认为正确而合适的事。

人生的智慧的重要之处，存在于一个正确的关系之中，在这个关系中，我们的注意力时而放
在当下，时而放在未来。把握好这个关系的平衡，我们才不会在当下与未来之间顾此失彼。
而当下才是唯一真实可靠的。

所有的桎梏都会使我们幸福。我们的认识、活动和联系的范围越狭广泛，我们的担忧、意愿
和恐惧也会增多。限制外在活动范围，我们就能够避免刺激意志的外部动因；限制精神活动
范围，我们就能消除刺激意志的内部动因。（就是减少欲望嘛。）

富有精神的对话或者理解，仅仅属于富有精神的社交。在庸俗的社交中，人们简直仇视富有
精神的东西。谁无法消受孤独，谁就无福消受自由；因为只有当一个人独自面对自己时，他
才会自由。

一般而论，每个人只能与自己保持最完整的一致，而不是与他的朋友，也不是与他的爱人。
因为每个人的个性与情感总会导致一种与他人不协调的东西，尽管这种不协调可能很小。

一个只依靠自己并且能够完完全全做自己的人，这种人就是最优秀的。

他反对与人交际，优秀的人抱团会被庸俗的人钻空子最终落俗，不承认”三个臭皮匠顶个诸
葛亮”，认为交际是人类相互之间在精神上的一种取暖方法。但是广义的讲，他也没有脱离
交际，他读别人的书或者信，自己著书让别人来读，或赞同不赞同彼此的观点，这就像现代
的网上交友一样。

他所说的优秀的人像特指哲学家一样，而我本就是一个平庸之人，为何非要自寻孤独呢，难
道只有这些离群索居这人才是幸福的？人们通过社交在精神上取暖并没有错，只要有所控制
不要坠入无休止仅为打发时间的活动就行。而他无时不在突出自己是一个精神能力的贵族，
看不起凡夫俗子，如此，他为何不上天呢？脱离大众的哲学家不是个好的哲学家。世界并不
是只有哲学就可运行，绝大多数的工作都需要合作，而现在的文明水平比与他那个时代大大
提高，此观点也不证自明。

他说多关注比我们活得差的人，可以找到心理的平衡，以免产生嫉妒。

纯粹的思想无法战胜我们欲望中的图景（印象），那么最好的办法就是借助与之相反的印象
来对之中和。

叔本华用了大量的篇幅告诫人员要保持健康，减少与社会的交往，保持心灵安宁，关注当下，
不要胡思乱想，多感恩自己拥有的东西，积极主动对待生活，正确看待不能左右的事情，不
要让自己无聊，做与自己能力相称的事，设想最坏的情况，做事时要有重点，在责罚的反思
中学习提高。

** 我们对他人的态度

为了在这个世界生存下去，我们就要具备一些先见之明和容人之量，有了先见之明，我们才
能避免受到伤害和损失；有了容人之量，我们才会避免争讼吵闹。

要有包容之心，能忍受任何人的存在，“林子大了什么鸟都有”，针对其特点进行利用是明
智的做法。与别人交谈时就把自己降低到和他们同一个水平，不要谈论与眼前之人有关的事
情，保持共同的情绪，营造出各谐的氛围。

假如一个人坚信，与我们对他的重要性相比，他可能会对我们重要得多；那么他就会立刻觉
得我们从他那里偷走了什么东西。他们就会试图报复我，并且要把他放在我们这里的东西夺
回来。（交往的平等原则。）意大利谚语： _谁不尊敬别人，谁就得到别人的尊敬。_

世界是邪恶的，在野蛮人那里，是人吃人；在文明人那里则是人骗人，我们称之为世道。所
以有时候我们要识别别人，也可能需要伪装自己。（实质上叔本华是不赞同伪装的。）

一个人可以忘掉一切的一切，但是他绝不会忘掉他自己的本质。因为性格是非常难以改变的。
人们所有的行为都会遵循一个内在的法则，这个法则使他在相同的处境之下，必然会采取相
同的行动，丝毫没有改变。（这就是我们要同渣男说不的理由，也是我们要包容一个爱人的
理由。）出于同一个道理，我们也不要太指望，在变化的环境中，一个人仍然会像先前一样，
做出相同的事情来。

在生活中或文学中碰到的背信弃义和愚不可及之举，我们犯不着为它们大动肝火。我们只要
把它们作为认识的材料即可，因为它们帮助我们对人类的性格有了新的看法，并将此牢记在
心。 

如果按照”一切非自然的东西都是不完美的”，是不是在否认学习。

做作即是欺诈，欺诈就是胆怯，而胆怯源于恐惧；惯于欺诈的人是对自己的谴责和诅咒，因
为我们想要表现出我们所不是的样子，装出更好的行径。

很多人并不是我们真正的忠诚的朋友，那些尊重和友情都是装出来的，当你告诉他自己遭受
不幸或者弱点时，他会非常高兴。

患难之交真的相当罕见吗？并非如此！一旦我们和一个人结为朋友，他就已经处在患难之中，
就让我们以钱来交了。（大叔，你是来搞笑的吧）

阿拉伯格言：“你的敌人不应知道的事情，也不可说给你的朋友听。”

擦亮眼睛，保持宽容，有所距离，沉默是金，言出必行。

葛拉西："使自己受欢迎的唯一法门，就是给臫披上最弱智的动物的外皮。"(否则会引起嫉
妒，所以男人喜欢站在矮子旁边，女人会找普通的丑女做伴，绝色倾城的女孩不会找到女友)

** 我们对世事和命运的态度

有三种御世之力：机智、实力和命运。我认为，运气可能是最重要的力量了。（在这里叔本
华明确表示承认运气的强大。）

命运是磨难的集合，物极必反，变化永恒，顺应天道，危机意识，早做准备，奋勇迎击。

* 人生的不同阶段

他认为人生为蠢材，必定死也为蠢材。（忽略教育的作用了，显然有问题）

他说人生的早期主要以认识现象（幻象），把幻象变为现实，就要活在意愿活动之中，但意
愿活动会带来不可避免的痛苦。在人生的后半截，我们则会顾忌不幸的到来，只为安心享受
下个尚可承受的当下。

回顾一生，因为我们对生命的记忆不多了，所以我们就觉得生活如此短暂。（人生需要纪录）

（不知道为什么是三十六岁之后，人生开始下坡路，这是怎么算出来的？好像他也不确定，
一会是四十年，一会是三十五年，可能是别人那里抄来的吧，并没有什么严格的依据）

年轻的时候是人生的积累，随着年龄的增长才能看透人生，但不能否定我们的昨天。

青年和老年之间的根本区别永远在于，青年的前景是生，而老年前景是死。

人生的智慧只是叔本华认为的智慧，有值得借鉴的地方，也有很多观点值得批判。我想他对
男女荣誉、骑士荣誉、孤独的论述无一不说明他在这些方面所受的伤害。