#+title: Debian11+Fvwm2.6定制桌面

我用Fvwm 有好长时间了，之前有段时间进行了较为深入的学习和研究，定制了自己的桌面
[[file:%E5%9C%A8Debian%E4%B8%8A%E7%94%A8FVWM%E5%81%9A%E8%87%AA%E5%B7%B1%E7%9A%84%E6%A1%8C%E9%9D%A2.org][在Debian上用Fvwm定制自已的桌面]]，用了一段时间后，还是感觉不太满意，反而觉得系统自
带的默认配置还可以，只是改了改快捷键，然后用了一年。而今又感觉有点单调，在
疑惑Fvwm是不是该被淘汰的时间，对流行的发行版进行充分考察，还是觉得Fvwm才是我的菜。

* 桌面的基本需求
每个人需要的桌面功能并不一样，但最基本的需求无非是在桌面上通过鼠标和键盘可以打开
自己想打开程序，按照自己的意愿调整程序窗口的位置、大小，全屏显示或者后台运行以及
在不想用的时候将其关闭。如果能提供一些便捷的功能，比如状态显示、时间显示等等的就
更加方便了。

具体是通过菜单、按钮或者快捷键中的哪种方式打开程序，什么方式来操作窗口，以及让系
统将常需要的信息显示在哪个位置是我们桌面需要配置的内容。大多数的发行版桌面反映的
是开发者的意图，我们只需要去适应他们的想法和他们的设计成果。用的多了，习惯了也没
有什么不妥，而我，需要的是自己的想法，适合自己电脑和使用习惯的想法，于是不可避免
地要更多的精力来折腾罢了。

* Fvwm2.6默认配置存在的不足

从正式使用FVWM2.5开始至今，主要用了两版配置，第一版是自己折腾的，第二版应该主要
算是FVWM2.6自带的（只不过修改了快捷键）。用得久了，还是发现有些问题。

1. 120像素宽面板靠屏幕右侧，对于小屏笔记本来说，工作区域有点窄。
2. 面板中包含的4X4虚拟桌面环境使用的很少，占的位置不少。
3. xosview 显示占用的区域仍然偏大，但显示的信息并不满足需求。
4. FvwmIconMan 利用率并不高，因为我不会同时开几十个程序，而且我更愿意用
   FvwmWinList 来切换窗口。
5. 只有通过菜单或者快捷键来启动程序，缺少按钮启动方式，对于不熟悉我电脑的人太不
   友好。
6. 没有关机对话框，每次重启和关机时都要通过命令窗口，多有不便。

* 桌面配置改进

1. 把FvwmButtons面板移到屏幕上方，由主菜单按钮、FvwmIconMan、FvwmPager、
   StanloneTray,Xosview、FvwmScript-DateTime 组成，程序启动、任务栏、虚拟桌面状
   态、系统托盘、时间、网络和电量状态等基本功能。
2. 去掉所有窗口的标题栏，使用FvwmIconMan 中右键菜单和快捷键盘来完成窗口位置、大
   小等调整以及窗口关闭功能。
3. 将虚拟桌面调整为4X1，即1个桌面4个页面，分别主要运行Emacs、Firefox、PcmanFm、
   其它程序，保持桌面条理。
4. 将Xosview 缩小只显示网络和电量状态条，其他详细信息，比如CPU/MEM/DISK等使用
   Conky 展示在桌面右侧。
5. 增加FvwmScript-Quit关机对话框。
6. 使用 pcmanfm 接管桌面，并设置桌面背景，可以在桌面上放点当前工作使用的文件，对
   陌生人更加友好。
7. 使用 plank 作为启动面板，放在窗口下方，智能隐藏，用鼠标启动程序更加便捷。同时能
   提醒自己电脑上究竟已经装了哪些程序。

* 需要安装的基本程序
#+begin_src bash -n -t -h 7 -w 40
  apt-get install xorg fvwm menu pcmanfm conky-all sudo hibernate acpi mpg123 imagemagick xscreensaver emacs vim-gtk fcitx fcitx-table-wubi firefox-esr xchm xpdf gimp gthumb vlc audacious recoll libreoffice build-essential automake autoconf m4  cmake bash xdm p7zip xarchiver p7zip-full arj lhasa rpm unrar-free zip axel manpages-zh  minicom libreoffice-l10n-zh-cn xloadimage inetutils-tools net-tools xosview stalonetray volumeicon-alsa git brasero locales global virtualenv pulseaudio enca sdcv archmage mplayer gnome-icon-theme gnome-icon-theme-extras pandoc gparted wireless-tools wpasupplicant plank
#+end_src

与原来相比，我使用pcmanfm 替代 rox ，同时使用 stalonetray,xosview,plank 这几个小
程序让使用更加方便。 

* 从Fvwm2.5 到 Fvwm2.6

  1. Fvwm2.6 没有 FvwmTaskbar 模块，使用 FvwmButtons 实现相同功能。
  2. 使用FvwmButtons Swallow xosview 时启动过程中总有点问题，最后解决方式是在
     StartFunction 中启动 xosview ，在 FvwmButtons 中Swallow 加上参数。
#+begin_src 
  *SystemTray: (40x30, Swallow(NoClose,UseOld) xosview \ 
  'Exec exec xosview -page -mem -cpus -disk -load -swap -cpu  -captions -labels',Frame 0)
#+end_src
  3. 设置查看manpage 使用的终端。 
#+begin_src
  InfoStoreAdd terminal xterm
#+end_src
  4. 限制窗口的最大尺寸。
#+begin_src
  Style * MaxWindowSize 100 100
#+end_src
  5. 设置 plank dock 的风格。
#+begin_src 
  Style plank !Title,!Handles,WindowListSkip,NeverFocus,BorderWidth 0
#+end_src
  6. 使用FvwmButtons 时设置尺寸的技巧，使用像素来设置行，可以较为直观地控制。
#+begin_src 
  PipeRead 'echo "*SystemTray: Geometry $[vp.width]x30+0+0"'
  *SystemTray: Rows 30
  *SystemTray: Columns $[vp.width]
#+end_src
  7. 系统默认 FvwmScript-DateTime 中设置有120像素宽度，需要根据 FvwmButtons 中的需
     要来修改。我的作法是把系统默认配置复制了一份到自己配置目录中按需求进行修改。 
#+begin_src 
  *SystemTray: (60x30, Swallow DateTime 'Module FvwmScript "$[fvwm_scrpt]/FvwmScript-DateTime"',Frame 0)
#+end_src
  8. stalonetray 也有自己的配置文件，特别是其中设尺寸的参数指的是在其中显示几图标
     的宽度。icon_size 指定了图标大小为18像素， geometry 指定了显示几个图标。6x1
     指的是显示6个图标到一排上。6个图标的宽度基本上要合 FvwmButtons 中设置的宽度一
     致，否则显示会出问题。

#+begin_src 
  *SystemTray: (110x30, Swallow(NoClose,UseOld) \
  stalonetray 'Exec exec stalonetray --config \
  "$[fvwm_home]/stalonetrayrc"', Frame 0)
#+end_src

#+begin_src 
  geometry 6x1
  icon_size 18
  max_geometry 6x1
#+end_src
  本作品采用[[http://creativecommons.org/licenses/by-nc-nd/3.0/deed.zh][知识共享署名-非商业性使用-禁止演绎 3.0 未本地化版本许可协议]] 进行许可。








