VBA精选实例解析

* 前言

** VBA 是什么？

VBA,Visual Basic for Applications是一种Visual Basic的一种宏语言，主要能用来扩展Windows的应用程序功能，特别是Microsoft Office软件。也可说是一种应用程序视觉化的Basic Sc​​ript。 1994年发行的Excel 5.0版本中，即具备了VBA的宏功能。只需要打开装机自带的Office，然后按下Alt+F11就自动进入编程和执行环境。

** VBA 能干啥？

许多高级程序员瞧不上VBA。因为程序员是有鄙视链的：汇编 >C >C++ >Python >Java及C#及PHP（这三者相互撕） >VB >HTML。在这长长的鄙视链中，甚至都没有VBA的位置。可是，VBA是图灵完备的。网络上有人专门证明VBA语言满足RULE110,即其图灵完备性，简单来说，一切可计算的问题都能计算，大多数编程语言能实现的大部分功能，VBA都能实现。它可以执行基本的算术运算、要以与OFFICE套件进行交互，读取写入修改其中数值和样式等，但又不仅限于此，它还可以调用WINDOWS API,与操作系统进行交互，读取写入修改本地文件，甚至操作与计算机联接的硬件设备。它可以只在后台进行计算，也可以开发出精美界面的应用。而且曾经一度，VBA语言编写的宏病毒还非常流行。举例具体地讲，花名册分类统计汇总、自动打印、试卷评分、倒计时、题库背记辅助应用等场景均能够高效实现。

** VBA 优点和缺点

环境不依赖，只需要打开装机自带的Office，然后按下Alt+F11就自动进入编程和执行环境上手简单。

学习曲线很平缓，甚至可以更简单的通过录制宏来解决写程序的问题，只需要在简单的代码基础上修修补补就可以执行。

与办公环境完美兼容，在Excel/Word/Powerpoint/Outlook/Access之间随便穿梭，比胶水语言还要简单易用。

分享性和移植性很强，几乎所有测试通过的程序放到别的机器上也可轻易执行（如果不考虑各种本地文件位置）。

** 阅读对象

本书主要通过各种实例讨论VBA编徎方法和技巧，主要是为Professional Service以及各行各业不写程序但是又严重依赖于Office的职场人士服务的。

** 内容安排

第一章简要介绍VBA的相关概念，第二章主要介绍EXCEL+VBA的几个项目，第三章讲OFFICE+VBA项目，第四章讲PPT+VBA项目。第五章分步介绍综合性大项目。

* VBA基础知识

作为一门程序设计语言，主要是通过文字将需要运算的内容表达出来，尔后由解释器和编译器转换成计算单元识别的低级语言进行运算后输出结果。

** 关键字、变量、字符串、数字、运算符和语句

比如：a=1+3，意指将1+3的结果赋给a 这个变量，和小学时学的方程中的变量一样。如果要将计算的结果显示出来，则要通过 messagebox 等方法。例如：messagebox cstr(a)，这句话的意思就是通过一个对话框将a这个值显示给用户，由于a是数字类型，所以通过cstr这个函数转换成字符串类型，这是由messagebox这个方法只能处理特定对象决定的。

项目|类型|说明
Public,Dim,Sub,Function|关键字|程序中的特定标记，说明其后的内容代表的意思
a|变量|可以代表任意对象，但需使用Dim 关键字提前声明
"a"|字符串|用双引号包围
1|数字|分整型、长整型、浮点型分别为Integer/Long/Float
+-*/&|运算符|分别是加减乘除和字符串的拼接符
If a>0 Then b="结果是：" & cstr(a)|语句|条件语句，意指当a 大于0时，将变量b 设置为“结果是：<a>”

** 过程控制语句

任何一门编程语言都离不开控制语句，主要分为条件语句和循环语句。

*** 条件语句

If 条件 Then 动作

或者
 
If 条件 Then
 动作
EndIf

意思是当满足条件时，执行后面的动作，当写在一行上时，不需要EndIf。

*** 循环语句

在自动化处理中，最重要的语句就是循环语句。只有掌握和学会运用循环语句才算是程序入门。在VBA中最常用有两种形式的循环语句。

**** For i=a to b Step s... Next i

当需要用到循环变量时，常常采用这种形式，特别是在Excel 中用得比较多，一般是在动作中使用循环变量来访问单元格，如果在Word 中，一般在动作中用循环变量按位置访问文档中的文字。举个Excel 的例子：
For r=1 to 10
    Cells(r,2)=r
Next r
这一小段代码的意思是在第二列的第1至10行填充序号。
**** While 条件 动作 Wend

这种语句的意思也是当满足条件时进入循环体执行动作。主要用在不需要循环变量的地方，以及要判断程序执行结束点的地方。举个例子：

i=1
While Cells(i,1)<>"" 
    Cells(i,3)=Cells(i,1) & Cells(i,2)
    i = i +1
Wend

这段代码的意思是从第1行第1列的单元格开始，直到遇到第1列中为空的单元格为止。可能有的朋友发现这里也有用i 当作循环变量，为什么也要用While 语句呢？这是个人习惯，用For 语句也是可以实现的，但要设置一个最大行号，实现如下：

For i=1 to 66536
    If Cells(i,1)="" Then
        Exit For
    EndIf
    Cells(i,3)=Cells(i,1) & Cells(i,2)
Next i
    
* EXCEL中VBA开发实践


* WORD中VBA开发实践

* PPT中VBA开发实践

* VBA综合应用实践
