* 数据处理
** 前言
很早以前就想系统性地记录这些年在数据处理方面积累的心得，但是毕竟学得比较杂，数据处理涵盖的范围又太广，有些无从下手的感觉。但是，特别是到现在定在信息保障室后，主要从事的工作中有很大一块是数据处理，有些新同志在这方面还比较缺少经验，想想整理整理知识分享大家已经到了必须要完成的地步了。希望能坚持下去，也算完成自己的心愿吧。
** 概念
什么是数据呢，其实数据本身只是代表一种事物，当其承载着信息时才有价值，而我们单位名叫信息保障室，名字是非常恰当的。前段时间，信息保障处的同志在和我交流时还说，信息保障室容易引起误会，应该改个名字。我不敢苟同，他们信息处指的是信息系统，而我们是信息数据，对于大部分人来说，可能分不清楚，但实际差别确实很大，没毛病。

我们面对的数据就是文字、表格、图像、音频、视频等,有个共同特点，都是有一定规律的信息。大家大部分不是助理工程师就是计算机技师，要做的就是从看似没有规律的数据中去找出规律，然后形标准的特定格式的数据，再进行深加工，形成图表、报告，以供首长掌握使用，辅助决策。

说到规律，可能有人不太赞同，说有的数据就没有规律。道家还讲天道归一呢，看的角度不同，得出的结论不同，也决定着找到的方法适用适用。比如说，一篇公文，有哪些规律呢？从存储上讲，如果是DOCX格式的，那他就是压缩包，是结构化数据，我可以解压他，然后提取里面的文字；从内容上讲，它有标题、发文字号、主送、正文、落款、版记等，从样式上看，黑体是一级标题、楷体是二级标题；从单字上看，我还可以统计每个字出现的频率，找出主题词；还可以看颜色、排版等等。表格就不讲了，图像视频也一样，有他的一些规律。

而数据处理要干啥呢？就是要利用这些规律找出我们关注的信息，进行格式化，深加工，形成领导们想要的产品。下面我将通过数据获取、数据整理、数据应用总体思路向大家介绍方法和经验。
** 工具
俗话说，公欲善其事，必先利其器。找到称手的工具相当重要，不能光靠一双手一支笔，这太原始了，而且处理不了复杂的数据，比如图像、处理不了大数据，比如全区人员信息。我到目前用过的工具有，处理文本的VIM\EMACS,处理表格的EXCEL，处理图像的PS、GIMP，处理视频的PRIMIER、会声会影。有个网站叫善用佳软，介绍一些好的软件，有些参考价值。当然，还有些涉及到的程序的方法，OFFICE套件中使用VBA，即通常讲的宏，在EXCEL、WORD、PPT中都可以使用，只有想不到，没有做不到。更加通用的PYTHON，在LINUX、WINDOWS系统上都可以使用，结合许多工具包在处理数据、图像、视频上可以说非常强大。
** 数据获取
*** 数据采集

有人工录入的和传感录入，当前部队主要方式是人工录入，比如人员、装备、地理环境等数据均是通过手工录入，而传感录入的例子之一比如营门出入管理系统采集到的一系列数据，比如防空雷达系统采集、定时照像机等、气象台等。应该说目录主要方式是人工，辅助方式是自动。人工的方式有随意性大、效率低，自动产生的数据都是海量的需要有工具进行处理。
*** 数据抓取
为什么要使用数据抓取？要知道现在社会上数据的来源很多，特别是互联网上的数据，可以说是海量，有的也很有用，我们要做的就是从中抓出有用的数据来。当然，由于数据量太大了，光靠手工查询和复制粘贴的话是肯定不够的，要运用一些工具和手段来进行自动化处理。比如说，我们假想设定一个关键字，让工具自动到网络上进行寻找并进行格式化处理。现在有许多人做的就是数据抓取的工作，比如说搞网络爬虫的，百度就是一个非常典型的例子。盛聪也做了一个网盘的搜索工具，可以通过关键字在网盘上找有用的数据。前段时间，我帮助刘参在网上下载一篇长文章，被卖广告的网站把内容分成的许多小段，我使用的PYTHON写了一小段代码，访问网址，只提取有用的信息，很快就做好了。
** 数据整理
*** 通过样式
主要针对的是WORD文档，WORD文档可以一次选中同一样式的文本，并进行复制、剪切、修改等操作。
*** 通过标签
主要是针对标记语言，比如HTML/XML等，实质上向PDF文件等也是标记语言，可以采取同样的方向进行处理。
*** 协议存储
主要指的是如二进制存储的文件，比如EXE文件就分头部和数据部，头部的长度是固定的，比如第1个字节存的是文件标记，第二个字节存的是头部的长度，第三个字节是数据的起始位置。这当然不准确，我只是举个例子。

其实每一种文件不是只有一种特点，采取一种方式，比如可以将WORD文档另存为HTML文件，再采取标签来进行处理。处理好后还可以另存回去。
** 数据存储
对于我们来讲，主要以数据库的方式进行存储。就是生成关系表。可以放在EXCEL中，因为EXCEL其实就是数据库。但跟真正的数据库差距还是有点大，比如速度比较慢，采取通常方式打开一个数据库，特别是数据量比较多的情况下，就会非常慢。所以，一般采用MYSQL、SQLITE、ORACLE、SQLSERVER等数据库进行存储。
*** 常用数据库特点
*** 音视频及图形图像的存储
** 数据应用

数据整理的最终目的是要应用，应用时有很多方式，比如形成报告，或者形成图形。比如，之前邝副要各个单位的点位，形成部署图。大家想想，采取怎样的方法最方便？我是这样处理的，统计了各个单位点位的经纬度坐标，然后，将其用SVG格式画成了图，而后覆盖到底图上去。有个什么好处呢，就是各单位的点位变化后，我可以很快地进行更新，还有就是10个点，或100个点，或都1000个点，都可以在5分钟内标成部署示意图。
*** 图形化
简单的图形化有，在EXCEL中将图生成折线图、饼图等
*** 查询
另外就是整理后可以随时通过查询生成报表，查询有哪些方法呢？
** 案例
*** 花名册
*** 题库
*** 网页文件抓取
*** 编制查询
*** 表格化

